# Generated by Django 3.2.7 on 2021-09-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Наименование товара')),
                ('image', models.ImageField(blank=True, upload_to='product_images/%y/%m/%d', verbose_name='Фото товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена товара')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('color', models.CharField(max_length=50, unique=True, verbose_name='Цвет товара')),
                ('size', models.PositiveSmallIntegerField(unique=True, verbose_name='Размер')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата поступления на склад')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории товара')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_1', models.PositiveSmallIntegerField()),
                ('category_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_pr', to='mainapp.product', to_field='size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productcategory'),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_1', models.CharField(max_length=50)),
                ('category_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_pr', to='mainapp.product', to_field='color')),
            ],
        ),
    ]
