# Generated by Django 3.2.7 on 2021-09-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Цвет товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, unique=True, verbose_name='Размер'),
        ),
    ]
