# Generated by Django 3.2.7 on 2021-09-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210920_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images/%y/%m/%d', verbose_name='Фото товара'),
        ),
    ]
