# Generated by Django 3.2.7 on 2021-10-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Размер'),
        ),
    ]
