# Generated by Django 3.2.7 on 2021-10-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211011_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Размер'),
        ),
    ]
