# Generated by Django 3.2.7 on 2021-10-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/%y/%m/%d', verbose_name='Фото товара'),
        ),
    ]
