# Generated by Django 3.2.7 on 2021-11-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'Формируется'), ('STP', 'Отправлено в обработку'), ('PD', 'Оплачено'), ('PRD', 'Обрабатывается'), ('RDY', 'Готово к выдаче'), ('CNC', 'Заказ отменён')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
